export const OPENAI_BASE_RECOGNITION_URL = import.meta.env
  .VITE_OPENAI_BASE_RECOGNITION_URL;
export const OPENAI_RECOGNITION_MODEL = import.meta.env
  .VITE_OPENAI_RECOGNITION_MODEL;
export const OPENAI_BASE_SUMMARIZE_URL = import.meta.env
  .VITE_OPENAI_BASE_SUMMARIZE_URL;
export const OPENAI_SUMMARIZE_MODEL = import.meta.env
  .VITE_OPENAI_SUMMARIZE_MODEL;
